name: Build QMK Keymap

on:
  push:
    branches: [ main, master ]
    paths:
      - 'keymap.c'
      - 'rules.mk'
      - 'config.h'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'keymap.c'
      - 'rules.mk'
      - 'config.h'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout keymap repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Build keymap with Docker
      run: |
        docker build -t qmk-markupboy .
        docker run --rm -v ${PWD}/build:/qmk_firmware/build qmk-markupboy bash -c "qmk compile -kb mode/m256wh -km markupboy && cp mode_m256wh_markupboy.* /qmk_firmware/build/ 2>/dev/null || find . -name 'mode_m256wh_markupboy.*' -exec cp {} /qmk_firmware/build/ \;"
        
    - name: List build artifacts
      run: |
        echo "Built firmware files:"
        find build/ -name "mode_m256wh_markupboy.*" -type f 2>/dev/null || echo "No firmware files found"
        ls -la build/
        
    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qmk-firmware-markupboy-${{ github.sha }}
        path: |
          build/*.bin
          build/*.hex
          build/*.uf2
        retention-days: 30
        
    - name: Generate release tag
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      id: tag
      run: |
        echo "tag=v$(date +'%Y%m%d-%H%M%S')-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        
    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.tag }}
        name: "QMK mode/m256wh - markupboy ${{ steps.tag.outputs.tag }}"
        body: |
          ## QMK Firmware Build
          
          **Keyboard:** Mode M256WH  
          **Keymap:** markupboy  
          **Commit:** ${{ github.sha }}  
          **Built:** ${{ github.run_id }}
          
          ### Files
          - `mode_m256wh_markupboy.bin` - Firmware binary for flashing
          
          ### How to Flash
          1. Download the `.bin` file
          2. Use [QMK Toolbox](https://github.com/qmk/qmk_toolbox) or your preferred flashing tool
          3. Flash the firmware to your keyboard
        files: |
          build/mode_m256wh_markupboy.bin
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}